# Generated by Django 3.1.7 on 2021-03-21 16:35

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('courier_id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('courier_type', models.CharField(choices=[('foot', 'foot'), ('bike', 'bike'), ('car', 'car')], max_length=4)),
                ('regions', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]), size=None)),
                ('working_hours', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(regex='^(([0,1][0-9])|(2[0-3])):[0-5][0-9][-](([0,1][0-9])|(2[0-3])):[0-5][0-9]')]), size=None)),
                ('rating', models.FloatField(null=True)),
                ('earnings', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(50)])),
                ('region', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('delivery_hours', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(regex='^(([0,1][0-9])|(2[0-3])):[0-5][0-9][-](([0,1][0-9])|(2[0-3])):[0-5][0-9]')]), size=None)),
            ],
        ),
    ]
