# Generated by Django 3.1.7 on 2021-03-27 21:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('courier_id', models.IntegerField(primary_key=True, serialize=False)),
                ('courier_type', models.CharField(choices=[('foot', '10'), ('bike', '15'), ('car', '50')], max_length=4)),
                ('regions', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('working_hours', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=12), size=None)),
                ('rating', models.FloatField(null=True)),
                ('earnings', models.IntegerField(default=0, null=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('region', models.IntegerField()),
                ('delivery_hours', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=12), size=None)),
                ('is_available', models.BooleanField(default=True)),
                ('complete_time', models.CharField(default=None, max_length=24, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_type', models.CharField(choices=[('foot', '2'), ('bike', '5'), ('car', '9')], max_length=4)),
                ('orders', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('finished_orders', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, null=True, size=None)),
                ('assign_time', models.CharField(default=None, max_length=24, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('courier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.courier')),
            ],
        ),
    ]
