# Generated by Django 3.1.7 on 2021-03-24 14:40

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('assign_time', models.DateTimeField(auto_now_add=True)),
                ('courier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.courier')),
            ],
        ),
    ]
