# Generated by Django 3.1.7 on 2021-03-28 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assign',
            old_name='orders',
            new_name='active_orders',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='is_available',
        ),
    ]
