# Generated by Django 3.1.7 on 2021-03-25 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20210325_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='used_weight',
        ),
    ]
