# Generated by Django 3.1.7 on 2021-03-24 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_assign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assign',
            old_name='courier_id',
            new_name='courier',
        ),
    ]
