# Generated by Django 3.1.7 on 2021-03-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20210328_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='courier_type',
            field=models.CharField(choices=[('foot', '10'), ('bike', '15'), ('car', '50')], error_messages={'invalid_choice': "This field must contain the following types: 'foot', 'bike' or 'car"}, max_length=4),
        ),
    ]
