# Generated by Django 3.1.7 on 2021-03-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_remove_courier_used_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='complete_time',
            field=models.CharField(default=None, max_length=24),
        ),
    ]
