# Generated by Django 3.1.7 on 2021-03-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20210324_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='assign_time',
            field=models.CharField(max_length=24),
        ),
    ]
