# Generated by Django 3.1.7 on 2021-03-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_auto_20210328_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='courier_type',
            field=models.CharField(choices=[('foot', '10'), ('bike', '15'), ('car', '50')], max_length=4),
        ),
    ]
