# Generated by Django 3.1.7 on 2021-03-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_auto_20210325_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='complete_time',
            field=models.CharField(default=None, max_length=24, null=True),
        ),
    ]
