# Generated by Django 3.1.7 on 2021-03-24 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_auto_20210324_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assign',
            old_name='courier',
            new_name='courier_id',
        ),
    ]
