# Generated by Django 3.1.7 on 2021-03-27 18:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_auto_20210327_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='completed_orders_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=[], null=True, size=None),
        ),
    ]
