# Generated by Django 3.1.7 on 2021-03-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_auto_20210324_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_availabe',
            field=models.BooleanField(default=True),
        ),
    ]
