# Generated by Django 3.1.7 on 2021-03-24 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_order_is_availabe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Orders',
        ),
    ]
