# Generated by Django 3.1.7 on 2021-03-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_auto_20210325_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='earnings',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
