# Generated by Django 3.1.7 on 2021-03-24 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_auto_20210324_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='is_availabe',
            new_name='is_available',
        ),
    ]
