# Generated by Django 3.1.7 on 2021-03-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_auto_20210324_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
